[package]
name = "user/rojo-testing"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
roact = "roblox/roact@1.4.4"
profileservice = "brittonfischer/profileservice@2.1.5"