[package]
name = "user/rojo-testing"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
roact = "roblox/roact@1.4.4"
profileservice = "brittonfischer/profileservice@2.1.5"
Trove = "sleitnick/trove@0.5.0"
Input = "sleitnick/input@2.1.1"
Component = "sleitnick/component@2.4.6"
Concur = "sleitnick/concur@0.1.2"
WaitFor = "sleitnick/wait-for@0.2.2"